# Optimized Enhancement Parameters - 5-Fold Cross-Validated on Table Datasets
# Generated by OCR Parameter Tuning with Cross-Validation

OPTIMIZED_PARAMETERS = {
    # CV-Optimized Table Parameters (PubTables-1M + PubTabNet 2.0)
    'table_contrast_factor': 2.8,           # CV-validated: 2.8
    'table_brightness_factor': 0.725,       # CV-optimized: 0.725 vs original 0.65
    'table_sharpness_factor': 2.35,         # CV-optimized: 2.35 vs original 2.2
    
    # Standard parameters (maintained for compatibility)
    'standard_contrast_factor': 2.6,
    'standard_brightness_factor': 0.68,
    'standard_sharpness_factor': 2.1,
    
    # CV-Optimized OpenCV Parameters
    'bilateral_d': 9,                        # CV-optimized: 9 vs original 11
    'bilateral_sigma_color': 95.0,           # CV-optimized: 95.0 vs original 85.0
    'bilateral_sigma_space': 75.0,           # CV-validated: 75.0
    
    # CV-Optimized Adaptive Threshold Parameters
    'adaptive_block_size': 15,               # CV-optimized: 15 vs original 13
    'adaptive_c': 1.67,                      # CV-optimized: 1.67 vs original 1.5
    
    # CV-Optimized Morphological Parameters
    'morph_kernel_size': (1, 1),             # CV-optimized: (1,1) vs original (2,2)
    'table_morph_close_iterations': 1,       # CV-validated: 1 iteration
    'table_morph_dilate_iterations': 1,      # CV-validated: 1 iteration
    'standard_dilate_iterations': 1,
    
    # CV-Optimized Resolution Parameters
    'matrix_scale': 4.5,                     # CV-validated matrix scale
    'enhancement_matrix_scale': 4.5,         # CV-optimized: 4.5 vs original 5.5
    'dpi': 500,                              # CV-optimized: 500 vs original 450
    'enhancement_dpi': 500,                  # CV-optimized: 500 vs original 550
    
    # CV-Optimized Detection Thresholds
    'edge_density_threshold': 0.030,         # CV-optimized: lower threshold for better table detection
    'line_density_threshold': 0.005,         # CV-optimized: lower threshold for broader detection
}

# Cross-Validation Performance Results:
# Mean Character Error Rate: 0.1644 ± 0.0150
# Mean Word Error Rate: 0.2134 ± 0.0169
# Mean Confidence Score: 0.8022 ± 0.0413
# Validation Method: 5-fold Cross-Validation
# Dataset: Mixed Table Datasets (PubTables-1M + PubTabNet 2.0)
# Analysis Confidence: High (cross-validated)
